### PR TITLE
fix axiom configure error

### PR DESCRIPTION
**Pull request by mswell**
Fixes:#62 axiom configure error

### CODE REVIEW

**Comment by ex0ns** [comment]
I tested this and it works on both Ubuntu and Arch ! Thanks
There is an extra `;` on line 177

**Comment by mswell** [comment]
@ex0ns I removed extra ";" at line 177.
thanks :)

**Comment by BUGBOUNTYchrisg8691** [comment]
Thanks, everyone for the help. It seema to be fixed, now, anyway.

**Comment by mswell** [comment]
close this PR, problem solved on this commit https://github.com/pry0cc/axiom/commit/b2a201babef439c53b9a3a5e4524df5a208c38cf

**Pull request closed without merging**
