### PR TITLE
Consider removing public key

### PR DESCRIPTION
**Pull request by kyleavery**
Not really a problem with the tool, but I usually keep a fork of this repo without your public key ;)

~~Haven't looked to see if the program needs configs/authorized_keys to exist. If not, you could probably add it to .gitignore without an issue.~~

Update: axiom-configure seems to work fine without authorized_keys, it created it for me.

### CODE REVIEW

**Comment by pry0cc** [comment]
It should work - if it breaks something I will come knocking :P

**Comment by pry0cc** [comment]
Screen Shot 2020-09-01 at 8 18 48 PM

Dude? Cmon.

**Comment by kyleavery** [comment]
Shoot, my bad. I swear I tested it with answering `y` to "would you like me to install this". Didn't think to try with `n`. Let me see if I can fix.

**Comment by pry0cc** [comment]
Maybe just blank would work :)

**Comment by kyleavery** [comment]
Not sure if this is what you'd want to do, but I just added a line that touches the file and it seems to work fine
https://github.com/kyleavery/axiom/commit/a3fe8383ed0c29e778033084df302e734db127e3

**Comment by pry0cc** [comment]
The problem is - it removes it if you already have axiom-configure previously ran. 

I don't know, I'll fix it.

**Comment by pry0cc** [comment]
Fuck now everybody has to run axiom-configure again.

Wow.

**Comment by pry0cc** [comment]
```
cp ~/.ssh/id_rsa.pub ~/.axiom/configs/authorized_keys
```

That should fix things for 99% of people. Putting for reference before we get a shit-storm of people complaining axiom is broken.

**Comment by pry0cc** [comment]
https://twitter.com/pry0cc/status/1300893439681327105?s=20

**Comment by pry0cc** [comment]
Hey  - I'm sorry if I was a little hotheaded. This is my fault because I should've seen this coming. Thank you so much for the contrib :)

**Pull request merged**
