### PR TITLE
Utilize Digital Ocean Projects

### PR DESCRIPTION
**Pull request by wdahlenburg**
This pull request is a work in progress. There are quite a few scripts in the interact folder, so I'll work through them incrementally. Please add any feedback.

Digital Ocean provides the ability to group resources into projects. I run a few droplets that I don't want to be accessible to the Axiom suite. I'm sure there are other people that don't necessarily want to mix Axiom related resources with pre-existing resources in their account.

Placing all Axiom related droplets into an Axiom project would allow for a cleaner experience. Currently axiom-ls lists out all droplets on the account, which can make it difficult to know what droplets I spun up with Axiom. 

I opened up a feature request with Digital Ocean to [improve the correlation between Projects and droplets](https://ideas.digitalocean.com/ideas/DAPI-I-10). Per the APIs current capabilities, it's not elegant to get project resources and filter the existing droplets off this information. 

* axiom-configure
  * Ask the user to select an existing project or to create a new one and store the project id in the configuration file
* axiom-init
  * Once the resource is created move the resource to the configured Axiom project, irrespective of the default project
* axiom-ls
  * Grab resources from project and filter the list of droplets whenever they are accessed

### CODE REVIEW

**Comment by wdahlenburg** [comment]
In dd84926 the changes to axiom-ls were mostly reverted. The do-functions.sh file cleaned up the code a lot. I used some jq magic in the instances function to ensure only project related resources are listed. 

I added the instance_ip function, which ensures only the filtered project resources are only searched.

**Comment by pry0cc** [comment]
Hey! I really appreciate the work you've done to implement spaces. Unfortunately, as were working to modularise axiom to eventually work with different providers, this would add a lot of extra complexity that would complicate things when we bring in other providers. 

As for any code cleanup - that's awesome 😎 keep sharing! Thanks!!

**Comment by wdahlenburg** [comment]
Hey @pry0cc. No worries. Let me know if you want to keep any portions of the commits and I can open up a different PR. 

Best of luck working to utilize other providers. I'm really interested to see where Axiom goes.

**Comment by Sy14r** [comment]
@pry0cc I was thinking about this feature. What if we implemented via tags?
Digital Ocean
AWS
Azure
GCP

all support tagging and I believe the API could be used in those cases to limit what axiom acts on to tagged resources. I was planning on doing two things if you're ok with the tag based solution:

1. Going to make all axiom commands by default only act on resources tagged axiom (and will have axiom created resources tagged with axiom by default). This way you can use axiom and it won't affect other non-axiom things you may be running in your cloud
2. Was going to add an axiom-project or axiom-workspace command to list tags in the cloud env and allow the user to create/select a tag so that only assets tagged with the selected tag would be affected. I envision if a user wants to have a workspace called 'testing' that the actual tag on the backend would be axiom-testing and the client would abstract the leading axiom- away from the user that way when axiom-workspace goes to list workspaces it looks for all tags and only prints out the tags starting with 'axiom-' split on the '-'.

I'm gonna do this in a test branch of my repo and you can see if you like it. I know it adds complexity but I think using tags is generic enough that the value would be worth it... thoughts?

**Pull request closed without merging**
