### PR TITLE
Updating the Arch install

### PR DESCRIPTION
**Pull request by JBarrskog**
The PR as requested.

I have not had time to set up a new VM to check that everything installs correctly yet. However, I double-checked all the package names in pacman, and copied stuff from my "hack_box"-setup script I used to setup my VM.

I am intending to verify that it works on a fresh install before I think it is ready to be merged.

Note: I removed mmv as I couldn't find any reference to it in the repo.

Note 2: I split the dependencies according to the wiki from the "extra" dependencies. Up to you whether the "wiki-deps" should be expected or installed as a courtesy...

Any feedback is welcome!

### CODE REVIEW

**Comment by 0xtavian** [comment]
@JBarrskog thanks, we'll need to try on a fresh setup before we merge. I've never used Arch but maybe i'll give this a shot sometime next week but cant promise anything. 

Also it seems like we are missing go install?

We can remove fzf (for now cuz its not used anywhere else atm). Also It would be great to remove doctl and instead add a Arch check to each account-helper.

https://github.com/pry0cc/axiom/blob/master/interact/account-helpers/do.sh#L37
https://github.com/pry0cc/axiom/blob/master/interact/account-helpers/azure.sh#L44
https://github.com/pry0cc/axiom/blob/master/interact/account-helpers/linode.sh#L52

**Comment by JBarrskog** [comment]
> I've never used Arch but maybe i'll give this a shot sometime next week but cant promise anything.
It's quite straight forward. Follow the guide on the Arch-wiki. Perhaps my script could be of some help as well. 
https://github.com/JBarrskog/InstallScripts/blob/main/arch_setup.sh

> Also it seems like we are missing go install and gopath?
I've added installation of go through pacman. The GOPATH is set at the configuration of zsh. I opted for using `which go` to retrieve the path of the binary.
 
> We can remove fzf (for now cuz its not used anywhere else atm). 
Removed fzf.

> Also It would be great to remove doctl and instead add a Arch check to each account-helper.
> https://github.com/pry0cc/axiom/blob/master/interact/account-helpers/do.sh#L37
> https://github.com/pry0cc/axiom/blob/master/interact/account-helpers/azure.sh#L44
> https://github.com/pry0cc/axiom/blob/master/interact/account-helpers/linode.sh#L52
Sorting this out now.

**Comment by JBarrskog** [comment]
Stupid me. Why do I keep clicking "close".....?!

**Comment by JBarrskog** [comment]
Ok, everything is updated (besides IBM). 

I checked on it a little. According to their Github, the installer is expected to work for systems running 'apt'. There is an installer in the AUR (Arch User Repo), but I would advise against it, as they are user submitted, and the user is advised to inspect the code of the packages.

If we can assume that Arch-users are (somewhat) advanced. Perhaps a statement suggesting them to inspect the AUR-repo, and make necessary changes and install it, before a re-run of the script?

**Pull request merged**
