### PR TITLE
Plugged project discovery naabu as a new module

### PR DESCRIPTION
**Pull request by 0xtavi**
I would also love to have json format output for axiom-scan. 

Mostly for naabu and httpx.

I didn't sort out how to do it yet. Will investigate.

### CODE REVIEW

**Comment by 0xtavian** [comment]
thanks, will be looking into this shortly. As for merging JSON with axiom-scan, https://github.com/pry0cc/axiom/blob/master/interact/axiom-scan#L179, is a good place to get familiar with. All the merging functionality is there.
```
    if [[ "$ext" == "json" ]]; then
        echo "Mode set to JSON.. Merging with jq."
        touch "$tmp/output/place"
        cat $tmp/output/* |  jq -s > $tmp/merge
   fi
   ```

Adding ^ after [merge_output() {](https://github.com/pry0cc/axiom/blob/122d269b315ad9d8bc37c364fc9ca5eea5a00cf0/interact/axiom-scan#L179)  in axiom-scan could likely work. Although I have not tried.

**Comment by 0xtavian** [comment]
@0xtavi

**Comment by 0xtavi** [comment]
Hi, I will try these and might come with another pull request.

I noticed were the logic resides, but I was unsure about the merging part.

**Comment by 0xtavian** [comment]
cool @0xtavi. Also delete images/provisioners/full.json as we already have naabu installed. https://github.com/pry0cc/axiom/blob/master/images/provisioners/full.json#L133

**Comment by 0xtavi** [comment]
Hopefully that's fine. I'm pretty noob with git :monkey_face:

**Comment by pry0cc** [comment]
Nice addition! Great work guys! :)

**Pull request merged**
