### PR TITLE
Naabu with nmap support

### PR DESCRIPTION
**Pull request by nbsriharsha**
When you run nmap with naabu, You cannot download the XML output as only one extension is allowed. This module is registered as a directory extension, So it could get all files. The Nmap output should be placed in the output directory and it automatically processes the backups created by cp while merging with `mmv` and creating a sorted list of naabu ports, Nmap merged XML and Nmap merged output.

Example
```bash 
axiom-scan ~/check.txt -m naabu-nmap -p - -rate 10000 -c 50 -nmap-cli $'\"nmap -sV -A -T4 -oX output/nmap.xml\"' -o out/
```

### CODE REVIEW

**Comment by nbsriharsha** [comment]
Also, I am concerned about this line. 

https://github.com/pry0cc/axiom/blob/master/interact/axiom-scan#L234

```
if [ $BASEOS == "Linux" ]; then 
     cp -r --backup=t $tmp/output/*/* $tmp/merge
else
      cp -r $tmp/output/*/* $tmp/merge
fi
```

It would create backup files when the baseos is linux only.  On other platforms, if the output file name is the same, it wouldn't overwrite and the file is missed. So this module depends on those backups and I am afraid that this would fail in systems other than Linux,

**Comment by nbsriharsha** [comment]
@0xtavian I have tested `mmv` for backups but it works for only files but it fails when there are directories in output like in aquatone.  I have written an alternate script to fix this issue. This changes the names of already existing files (ex a.txt to a1.txt).     Please look into it and let me know. 

Also after this logic, we can use `mmv` to append text files and leave other files as it is.

**Comment by nbsriharsha** [comment]
@0xtavian Also, In this particular line, there is 

https://github.com/pry0cc/axiom/blob/master/interact/axiom-scan#L236

```bash
rm -rf "$outfile"
```

When the quotes are appended it wouldn't delete the dir/file. Also if your intention is to remove the directory then this should not be done, because there can be other files in that directory.

**Comment by 0xtavian** [comment]
thanks @nbsriharsha. this looks awesome. will check it out today. As for that line, I am open to changes, just keep in mind we do that just in case someone specifies an output file or folder but there is already a folder or file in that location. What do you suppose we do instead?

**Comment by nbsriharsha** [comment]
@0xtavian The script which I have written would fix that issue. when there is already a file in the location with the same name it would create a backup file. (say exists.txt is already there it would create exists1.txt). 

For the directories, If the directory already exists that would be fine. we just move things in that.  Also why I have raised this question is if someone is doing a continuous scan then he would be saving in the same directory like me.   So I don't want the older files to be deleted.

**Comment by 0xtavian** [comment]
@nbsriharsha sorry for the delayed response. Testing this doesnt seem to work with modules that output to a folder, such a gowitness. paramspider etc. still debugging it.

**Comment by nbsriharsha** [comment]
@0xtavian I have just tried this on gowitness, It works fine for me

image


image

**Comment by nbsriharsha** [comment]
@0xtavian I found the issue, this doesn't work for relative paths in output.  If we add `cd $start` before this line. It works

https://github.com/pry0cc/axiom/blob/naabu-nmap/interact/axiom-scan#L266

**Comment by 0xtavian** [comment]
@nbsriharsha merged :) thanks again.

**Comment by 0xtavian** [comment]
@nbsriharsha while i like this idea. unfortunately when downloading/merging tens of thousands of files in a directory , screenshots for example, it takes an incredibly long time as its iterating over each screenshot and comparing the file names for duplicates. I might end up reverting this or making this optional somehow

**Pull request merged**
