### PR TITLE
Adding support for doas

### PR DESCRIPTION
**Pull request by JBarrskog**
I was considering better ways to execute the commands than 'eval', but
settled on it eventually.

### CODE REVIEW

**Comment by JBarrskog** [comment]
I have settled to opt for 'doas' instead of 'sudo' on my machines. The config-script is problematic it only uses 'sudo'. This PR checks if 'doas' is installed, and uses it. Otherwise, reverting do 'sudo'.

**Comment by 0xtavian** [comment]
@JBarrskog whats wrong with using sudo?

**Comment by JBarrskog** [comment]
Well, nothing really. On my Arch-machines I opted to run it instead, and can thus not rely on sudo being installed. 

It seems like consensus say it is more lightweight and less complex as it is more aimed at single/few user systems as it lacks some of the complexity of sudo.

Nevertheless, I found a packages on the Arch User Repository with doas packaged with the sudo-command. This is an alternative for users in my position, but it seems more straight forward to work around the dependency in the package. 

On the other hand, this PR will slightly reduce readability of the code.

**Comment by JBarrskog** [comment]
Oh, didn’t mean to close it… 😅

**Comment by 0xtavian** [comment]
If you can submit a PR that adds the following Packages to Arch I'd happily merge https://github.com/pry0cc/axiom/blob/master/interact/axiom-configure#L68-L79. As you said this PR affects readability and doesnt fix the monitory of issues with our Arch install.

**Pull request closed without merging**
