### PR TITLE
Update default.json

### PR DESCRIPTION
**Pull request by random-robbie**
Updated golang to 1.19 to allow go witness to install properly

### CODE REVIEW

**Comment by 0xtavian** [comment]
@random-robbie testing this and seeing the same issue mentioned here https://github.com/pry0cc/axiom/pull/604 please
Lmk if you disagree

**Comment by random-robbie** [comment]
Most tools I know are working in my build it wasn't til I tried gowitness I got errors and tried to install in Mac and got a module issue moaning I needed above 1.17 to run go witness.

**Comment by 0xtavian** [comment]
@random-robbie do you mind showing me the output of `ls /home/op/go/bin`? please and thank you.

**Comment by p0mbe** [comment]
I think the workaround is to download the executable after the instances have been created. Its what I do and works.

**Comment by 0xtavian** [comment]
@p0mbe you mean for gowitness? See this issue with another temp fix https://github.com/pry0cc/axiom/issues/601

another thing with gowitness is it seems their pre made binaries aren’t from the latest code. Which (probably) isn’t much better than using their docker image as my temp fix suggests. 

If we wanted to just download the binaries instead of building from [source](https://github.com/pry0cc/axiom/blob/1998da9acbe54641eb4dd122a66406b7a4b8da11/images/provisioners/default.json#L217) we could totally just replace go install command with a wget command to download the binary.

**Comment by 0xtavian** [comment]
> I think the workaround is to download the executable after the instances have been created. Its what I do and works.

But yea this totally works too :) there are many ways to skin the proverbial cat

**Comment by p0mbe** [comment]
> @p0mbe you mean for gowitness? See this issue with another temp fix #601
> 
> another thing with gowitness is it seems their pre made binaries aren’t from the latest code. Which (probably) isn’t much better than using their docker image as my temp fix suggests.
> 
> If we wanted to just download the binaries instead of building from [source](https://github.com/pry0cc/axiom/blob/1998da9acbe54641eb4dd122a66406b7a4b8da11/images/provisioners/default.json#L217) we could totally just replace go install command with a wget command to download the binary.

Yes, i use wget to download the binary and it works fine. Its best till this golang issue is sorted, or best a docker image

**Comment by 0xtavian** [comment]
Thanks guys I added this to master without merging. https://github.com/pry0cc/axiom/issues/601#issuecomment-1242608642

**Pull request closed without merging**
