### PR TITLE
axiom-init/axiom-build: Extract notify command to set it accordingly to hosts OS 

### PR DESCRIPTION
**Pull request by riedeljan**
`notify-send` only works on Ubuntu like systems but not e.g. on OSX.

In this PR I extracted the command so we can source it from `interact/includes/system-notification.sh` as `$NOTIFY_CMD` already fitted to the current host OS (now Ubuntu likes and OSX).

### CODE REVIEW

**Comment by pry0cc** [comment]
I have actually done this myself, but just by making my own notify-send script with applescript, we had the same idea :D 

Thanks so much for writing it! Looks great!!

image

**Comment by riedeljan** [comment]
I have to be blind, just skipped that step of the readme when I was reading it ^^ You're welcome though!

**Comment by pry0cc** [comment]
I was going to add it eventually, but there was no driver. I'm fanatic now though its built-in!!

You're awesome <3 Do you use axiom a lot?

**Comment by pry0cc** [comment]
Agh it seems its mis-formatting...
image

**Comment by pry0cc** [comment]
Ugh
image

**Comment by riedeljan** [comment]
Damn, I just tested it again before submission and it worked fine for me.
What WM are you using?

**Comment by pry0cc** [comment]
i3wm / dunst

Latest commit fixes it.

image

**Comment by riedeljan** [comment]
I'm just diggin' into it after I watched it for several weeks now. But it's great so far and I think there's _lots_ of capability.
Also I'm thinking of several ways to build customized (scheduled) workers with axiom and other stuff.. so many Ideas

**Comment by pry0cc** [comment]
Can you join the 0x00sec discord?

Would love to chat further there.

https://discord.gg/c6BHVfn

**Comment by riedeljan** [comment]
Ah I see now.. I screwed up my copy&paste game :D
Next time I'll just boot my *nix device with i3 and test it against that one too.

**Comment by riedeljan** [comment]
Already there. Just ping me @ dnc#3391

**Pull request merged**
