### PR TITLE
Fix one syntax error

### PR DESCRIPTION
**Pull request by mswell**

### CODE REVIEW

**Comment by pry0cc** [comment]
Forgive me, but what is this PR actually doing?

**Comment by mswell** [comment]
it was just a correction of how axiom was written, in the axiom-configure part of the readme :smile:

**Comment by pry0cc** [comment]
I don’t literally see what it’s changed :P am I being dumb here? :P

**Comment by mswell** [comment]
see in this image

<a href="https://ibb.co/XVvB154">axion</a>

**Comment by pry0cc** [comment]
Ahahaha! 

Oh I see it now! Thanks! I’m so dumb :P I stared at this so long dude. Merged.

**Comment by mswell** [comment]
relax :smile:

**Pull request merged**
