### PR TITLE
Add dalfox installation

### PR DESCRIPTION
**Pull request by hahwul**
Add dalfox installation
Since dalfox supports snapcraft and homebrew, I added it as snap.

snapcraft
```
$ snap install dalfox
```

homebrew
```
$ brew tap hahwul/dalfox
$ brew install dalfox
```

### CODE REVIEW

**Comment by hahwul** [comment]
here :D 
https://snapcraft.io/dalfox

**Comment by pry0cc** [comment]
Hey buddy, sorry I missed this a while back. Just got sorted moving and now I can sit down and focus. Would it be possible to resolve the merge conflicts as we just added the more modular custom images functionality?

**Comment by hahwul** [comment]
Hello again @pry0cc :D 
Um, Close the this PR and rewrite json file for resolve the merge conflicts, and add new PR it again. I think this is better. 

Is this file? 
https://github.com/pry0cc/axiom/blob/master/images/axiom.json

**Comment by hahwul** [comment]
@pry0cc 
And one thing I'm worried about is that Dalfox is currently applying for both go-get install and snapcraft, but I don't know which one is better to write. 

go-get: dev version
snapcraft: release version 
                 
Of course, it's best to use a release. but I afraid gonna be causing abnormal behavior from snapcraft's sandboxing policy 😭

**Comment by pry0cc** [comment]
Possible to fix the merge conflicts?

**Comment by hahwul** [comment]
@pry0cc 
I got it. I will do PR again after a new fork!

**Pull request closed without merging**
