### PR TITLE
Update subfinder

### PR DESCRIPTION
**Pull request by mswell**
Update subfinder and formatting and beautifying the JSON

### CODE REVIEW

**Comment by mswell** [comment]
What is EditorConfig?
EditorConfig helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems.

[editorconfig site](https://editorconfig.org/)

**Comment by pry0cc** [comment]
Awesome, would it be possible to resolve the conflicts?

**Comment by pry0cc** [comment]
Hmmmmmm

**Comment by mswell** [comment]
Conflict 2 resolved :)

**Pull request merged**
