### PR TITLE
Add clipboard sync feature

### PR DESCRIPTION
**Pull request by false-vacuum**
Hello! 

This PR would provide an easy way to sync the clipboard on remote hosts to the local clipboard. It uses a simple go utility called lemonade that runs as a server on your local machine. The same program can then be installed on the remote servers via a deployment profile. You can then pipe text into lemonade and it will show up in your clipboard! 

_Also, Neovim will automatically detect the lemonade binary_ and anything that gets put into the "unnamedplus" clipboard will be piped into lemonade, and thus sent back to your local clipboard. So you can yank text from vim on a remote machine, and it will show up in your local clipboard. 

I have this working with my X11 clipboard on Arch Linux, but it should work on most systems(even windows). More info on lemonade can be found here:
https://github.com/lemonade-command/lemonade

## Usage 
```bash
axiom-select foo
# install lemonade on remote server
axiom-deploy lemonade

# connect to remote server with new "sync-clipboard"
axiom-ssh foo --sync-clipboard
# or
axiom-connect --sync-clipboard

# do stuff
echo "this should show up in your local clipboard" | lemonade copy
```

## Requirements 
This assumes that lemonade is installed on your machine. If it's not I just exit and print an error message. Lemonade can be installed as follows.
```bash
go get -d github.com/lemonade-command/lemonade
cd $GOPATH/src/github.com/lemonade-command/lemonade/
make install
```

## Thank you!
I'd be more than happy to improve on this if it's something people may be interested in. I also have my tmux config setup to pipe its buffer to lemonade.  Thank you so much for sharing this project!!

### CODE REVIEW

**Comment by pry0cc** [comment]
Oh my god this is so awesome!!!!

As you can see... I've been busy. Could you be so kind as to fix the merge conflicts? Thank you! I'm so excited to try this out!

**Comment by false-vacuum** [comment]
@pry0cc No problem! I just resolved the conflicts and tested those changes. Let me know if you have any questions or anything. Thank you again!

**Comment by false-vacuum** [comment]
Sorry about the excessive commits. I got confused with the spacing in "interact/axiom-ssh". I just resolved the conflicts again and matched your indentation in the current master. @pry0cc

**Comment by pry0cc** [comment]
Hey!! Would it be possible to put the functions.sh code inside the provider/do-functions.sh? Just because that is what is getting included - we probably need to do some re-organization (my responsibility). 

Really want to get this patched soon in, epic PR.

**Comment by false-vacuum** [comment]
@pry0cc  Just to clarify, you would like me to move the "start_lemonade_server" function from "interact/includes/functions.sh" to "providers/do-functions.sh"?

Maybe I'm missing something, but I don't see include for that.

I would have to source "providers/do-functions.sh" in interact/axiom-ssh in order to get that to work since there isn't already an include for that script. 

No problem, just wanna make sure I understand.

**Comment by pry0cc** [comment]
Hey man, sorry super late, these PR's get thrown to the bottom of the pile but I've crunched through like 10 today 👍  :D

So - functions.sh exists, yes, but it gets overwritten when you run axiom-build. The ruby program `Axiom-provider do` builds a custom image for you using the pieces inside ~/.axiom/images and ~/.axiom/providers

Putting the function code into ~/.axiom/providers/do-functions.sh (and all the other ones) will make it accessible to different providers. We probably need a *core* functions space but I'm trying really hard to make our trajectory toward cross-cloud really smooth. Maybe just for DO for now?

**Comment by pry0cc** [comment]
Heya :D 

it's been quite a while - I'd love to merge this one.

Is there any way at all you can merge it to ~/.axiom/providers/do-functions.sh and test and re-PR? Being your code you know it best and how to use it - would be really dope if you could do that for us <3

Thanks

**Comment by 0xtavian** [comment]
Closing as stale

**Pull request closed without merging**
